# Site Identity
title: Electronic Dream Plant
description: Self-hosted music portfolio

# URL Structure
url: "https://www.ox1digital.co.uk"
baseurl: "/music"

# Collections Logic
collections:
  tracks:
    output: true
