title: Electronic Dream Plant
url: "https://www.ox1digital.co.uk"
baseurl: "" # Change this to empty

collections:
  tracks:
    output: true

# Add this to ensure these folders are copied to the final site
include: [assets]
